games-rpg/lipsofsuna-0.8.0 (buggy, use live-ebuild)
There is a bug with OGRE:
/usr/include/OGRE/OgreSharedPtr.h: In instantiation of ‘Ogre::SharedPtr<T>::SharedPtr(const Ogre::SharedPtr<Y>&) [with Y = Ogre::Resource; T = Ogre::Skeleton]’:
../src/lipsofsuna/render/internal/render-mesh-builder.cpp:379:38:   required from here
/usr/include/OGRE/OgreSharedPtr.h:202:28: error: invalid conversion from ‘Ogre::Resource*’ to ‘Ogre::Skeleton*’ [-fpermissive]